### ISSUE TITLE
请问登录返回的是ok但是为什么下载的时候总是无法成功呢

### ISSUE THREAD

**Issue by KonseXyu** [jlhg/mox#1]
![image](https://user-images.githubusercontent.com/56070680/209509148-b83028f6-2e00-41d9-bd66-75296fa853f7.png)

**Comment by cldotdev** [comment]
1. 原本抓的下載網址是 VIP2 線路，這個只有 VIP 才能用，新版已改回 VIP 線路，免費跟付費用戶都可以使用。
2. 下載失敗有可能已達到每日限額，新版已加入狀態碼 403 判斷並印出錯誤訊息。

**Comment by KonseXyu** [comment]
是第二個問題，感謝！
